---
name: Build
"on":
  push:
    branches:
      - master
      - main
      - staging
      - develop
    tags:
      - r*
  pull_request:
    branches:
      - master
      - main
      - staging
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Build
        run: make all
      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage/test.cov
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Build Release
        run: make -j$(cat /proc/cpuinfo | grep processor | wc -l) release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/r')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            callback-linux-arm.tar.gz
            callback-linux-arm64.tar.gz
            callback-linux-x86_64.tar.gz
            callback-linux-i386.tar.gz
            callback-windows-i386.zip
            callback-windows-x86_64.zip
            callback-darwin-x86_64.tar.gz
            callback-darwin-arm64.tar.gz
            callback-freebsd-x86_64.tar.gz